FROM node:20-alpine

RUN apk add --no-cache openssl openssl-dev wget

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .
RUN npx prisma generate

COPY entrypoint.prod.sh ./
RUN chmod +x entrypoint.prod.sh

EXPOSE 3000

ENTRYPOINT ["./entrypoint.prod.sh"]
